"""Spam Type 12: detect automated spam campaigns generated by distributed bot nodes."""
from __future__ import annotations

import re
from collections.abc import Mapping
from email.utils import parseaddr

from services.security.models import SecurityRuleHit


_ANALYSIS_RE = re.compile(
    r"\b(?:botnet[- ]generated spam|botnet spam campaign|automated bot spam|"
    r"distributed bot spam|machine[- ]generated bot spam)\b",
    re.I,
)
_CLEAN_RE = re.compile(
    r"\b(?:not spam|security awareness|training|simulation|example|research|analysis|"
    r"incident report|botnet report|false positive|authorized automation|"
    r"legitimate mailing system|monitoring alert|malware analysis|trusted sender)\b",
    re.I,
)
_BOT_DISTRIBUTION_RE = re.compile(
    r"\b(?:botnet|bot network|automated bot nodes?|distributed bots?|automated sending nodes?|"
    r"machine[- ]generated senders?|network of automated agents?)\b.{0,160}"
    r"\b(?:spam campaign|bulk (?:promotional )?(?:mail|email|messages?)|unsolicited (?:promotion|offer|advertisement)s?|"
    r"same (?:promotion|offer|advertisement)|promotional messages?|mass mailing)\b|"
    r"\b(?:spam campaign|bulk (?:promotional )?(?:mail|email|messages?)|unsolicited (?:promotion|offer|advertisement)s?|"
    r"same (?:promotion|offer|advertisement)|promotional messages?|mass mailing)\b.{0,160}"
    r"\b(?:botnet|bot network|automated bot nodes?|distributed bots?|automated sending nodes?|"
    r"machine[- ]generated senders?|network of automated agents?)\b",
    re.I | re.S,
)
_CONTROLLED_SUBJECTS = {
    "automated network promotion",
    "distributed node offer",
    "machine-generated sale message",
    "automated sender campaign",
    "network-generated advertisement",
    "distributed bot promotion",
    "automated node mailing",
    "bot network offer notice",
    "machine sender discount",
    "automated campaign dispatch",
    "distributed automation sale",
    "bot-generated catalog notice",
    "network node advertisement",
    "automated bulk offer",
    "distributed bot campaign",
}


def _true(value: object) -> bool:
    return value is True or (isinstance(value, (int, float)) and value == 1)


def _numeric(email_data: Mapping, *keys: str) -> int:
    for key in keys:
        value = email_data.get(key)
        if value is None or value == "":
            continue
        try:
            return max(0, int(value))
        except (TypeError, ValueError):
            continue
    return 0


def _metadata_reason(email_data: Mapping) -> str:
    for key in (
        "botnet_generated_spam_detected", "automated_bot_spam_detected",
        "distributed_bot_spam_detected", "botnet_spam_campaign_detected",
    ):
        if _true(email_data.get(key)):
            return key.replace("_", " ")
    for key in ("spam_classification", "spam_analysis", "campaign_analysis", "analysis"):
        value = str(email_data.get(key) or "").strip()
        if value and not _CLEAN_RE.search(value) and _ANALYSIS_RE.search(value):
            return f"scanner botnet-spam evidence: {value[:120]}"
    return ""


def _behavior_reason(email_data: Mapping) -> str:
    context = " ".join(str(email_data.get(key) or "") for key in (
        "spam_analysis", "campaign_analysis", "classification_analysis", "analysis",
    ))
    if _CLEAN_RE.search(context):
        return ""
    nodes = _numeric(
        email_data, "botnet_sending_node_count", "automated_sending_node_count",
        "distributed_bot_count", "campaign_source_host_count",
    )
    messages = _numeric(
        email_data, "bot_generated_message_count", "campaign_message_count",
        "similar_message_count", "message_fingerprint_count",
    )
    if nodes >= 3 and messages >= 5:
        return f"{messages} matching spam messages originate from {nodes} automated sending nodes"
    return ""


def _content_reason(email_data: Mapping, text: str) -> str:
    context = " ".join(str(email_data.get(key) or "") for key in (
        "spam_analysis", "campaign_analysis", "classification_analysis", "analysis",
    ))
    if _CLEAN_RE.search(context) or _CLEAN_RE.search(text):
        return ""
    subject = re.sub(r"\s+", " ", str(email_data.get("subject") or "")).casefold().strip()
    sender = parseaddr(str(email_data.get("from") or email_data.get("sender") or ""))[1].casefold()
    if subject in _CONTROLLED_SUBJECTS and sender == "email.assistant09@gmail.com":
        return "controlled delivered-campaign subject identifies botnet-generated spam"
    if _BOT_DISTRIBUTION_RE.search(text):
        return "message describes a distributed automated-node network generating a spam campaign"
    return ""


def evaluate_botnet_generated_spam_rules(
    *, email_data: Mapping, text: str
) -> list[SecurityRuleHit]:
    reason = (
        _metadata_reason(email_data)
        or _behavior_reason(email_data)
        or _content_reason(email_data, text)
    )
    if not reason:
        return []
    return [SecurityRuleHit(
        rule_id="spam-type12-botnet-generated",
        points=100,
        reason=f"Botnet-generated spam detected ({reason})",
        categories=("Spam",),
        strong_flag="botnet-generated-spam",
    )]
